### ISSUE TITLE
TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by ghost** [romseguy/redux-devtools-chart-monitor#19]
I just followed the instructions, pretty straight forward, but I'm getting these error:

```
TypeError: Cannot read property 'object' of undefined
./node_modules/redux-devtools-chart-monitor/lib/Chart.js

  62 | }(_react.Component);
  63 | 
  64 | Chart.propTypes = {
> 65 |   state: _react.PropTypes.object,
  66 |   rootKeyName: _react.PropTypes.string,
  67 |   pushMethod: _react.PropTypes.oneOf(['push', 'unshift']),
  68 |   tree: _react.PropTypes.shape({
```
I'm getting these error even before use the component in my `Monitor` component, I'm only importing it 
`import ChartMonitor from 'redux-devtools-chart-monitor'`

I am using the version `1.6.1`

**Comment by baronnoraz** [comment]
I'm running into the exact same problem with a vanilla install.

**Comment by baronnoraz** [comment]
I'm having issues with DiffMonitor too, but I think the reason is that both of these monitors are not working with the latest React 16 release.  Both seem to work fine on 15.  I believe some things changed with 15's React.PropTypes to 16's prop-types: https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by gabrielmicko** [comment]
Same here! Could you please fix it?

**Comment by gabrielmicko** [comment]
Seems like there is an open pr for this issue which has not been merged yet. 👎

**Comment by gabrielmicko** [comment]
Please @romseguy merge my PR so we can use it.
